### ISSUE TITLE
LinguistTools are not available under Linux and MacOSX toolchains

### ISSUE THREAD

**Issue by lighterowl** [justdan96/tsmuxer_build#2]
It is impossible to use the `LinguistTools` CMake module under Linux :
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```

and Mac OS X:
```
CMake Error at /usr/lib/osxcross/macports/pkgs/opt/local/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake
```

The issue on Linux can be solved by installing `qttools5-dev`, but I have no idea what to do about the Mac environment.

**Comment by justdan96** [comment]
I'll get on this soon

**Comment by justdan96** [comment]
I am adding qttools5-dev for Linux now. For the issues with Mac - I may have a solution. 

With osxcross although we have Mac versions of Qt tools installed we are actually using the Linux versions - see moc, rcc and uic being replaced in the Dockerfile. So we may be able to copy the binaries and CMake configuration files for Linux to the Mac folders and it can work.

**Comment by justdan96** [comment]
I've tested with your branch and can build it successfully with this commit: https://github.com/justdan96/tsmuxer_build/commit/a9d86cbd2e53bcd42ade1ff71553f90e7bf81b8d

**Comment by jcdr428** [comment]
@justdan96 Still in 'To do' in 2.7.0 automation ?

**Comment by justdan96** [comment]
Thanks for letting me know, I'll move it across
